spring:
  application:
    name: monitoring-demo

management:
  endpoints:
    web:
      base-path: new-api/welcome/actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server: localhost
  port: 8089

